---
- name: Deploy Holiday Events Application
  hosts: deployment_servers
  become: yes

  tasks:
    - name: Clean up existing project directory if it exists
      file:
        path: "/home/lotan/holidayevent"
        state: absent

    - name: Clone the latest code from GitHub directly onto the VM
      shell: "git clone https://github.com/lotanbh/holidayevent.git /home/lotan/holidayevent"

    - name: Build the Docker image directly inside the VM
      shell: "docker build -t holiday-app:latest /home/lotan/holidayevent"

    - name: Deploy application using Docker Compose (Bonus Task)
      shell: "docker compose -f /home/lotan/holidayevent/docker-compose.yml up -d --build"

    # - name: Stop old container if running
    #   shell: "docker stop holiday-container"
    #   ignore_errors: yes

    # - name: Remove old container if exists
    #   shell: "docker rm holiday-container"
    #   ignore_errors: yes

    # - name: Start the new container on port 3000
    #   shell: "docker run -d -p 3000:3000 --name holiday-container holiday-app:latest"

    # NEW STEP: Wait 3 seconds for Node.js to initialize
    - name: Wait for application to initialize
      pause:
        seconds: 3

    - name: Run a strict health check
      shell: "curl -s http://localhost:3000/health"
      register: curl_output
      # This forces Ansible to fail if the response doesn't contain "healthy"
      failed_when: "'healthy' not in curl_output.stdout"

    - name: Show health check response
      debug:
        msg: "Server response is valid and running: {{ curl_output.stdout }}"

